Support for a `qualityGateStatus` output variable
SonarSource/sonarqube-quality-gate-action pull request #14
Opened 2022-03-11 05:37 UTC by aldass

Added support for a `qualityGateStatus` output variable. From the action, this variable is set to a value of `PASSED`, `WARN` or `FAILED`. It can optionally be used as follows below.

The motivation for this change is the need to be able to programmatically use the _SonarQube Quality Gate_ value in other parts of a complex GitHub workflow via the standard GitHub Workflow syntax conventions.

```yaml
- name: SonarQube Quality Gate check
  id: sqQualityGateCk # id can be any uniqe value throught the yml file
  uses: sonarsource/sonarqube-quality-gate-action@master
  with:
    scanMetadataReportFile: target/sonar/report-task.txt
- name: "Example show SonarQube Quality Gate Status value"
  run: echo "The Status is ${{ steps.sqQualityGateCk.outputs.qualityGateStatus }}"
```

2022-06-05 13:37 UTC, kubamarchwicki commented
:rocket: that's a super helpful change when one looks for ways to customize the pipelines and sonar notifications (beyond the PR decorations). We use sonarcloud for some of our private projects and this simple change will greatly enhance and simplify some of our build pipelines.

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource requested changes
Hi @aldass!

Thank you very much for your contribution! I've added some change requests, mainly nitpicks. And I would align with the common practice of naming action output variables using lowercased and hyphened words, rather than camelcase.

Finally, could you add 3 extra assertions in the unit tests ([example here](https://github.com/SonarSource/sonarqube-quality-gate-action/blob/master/test/check-quality-gate-test.bats#L68)) 🙏 ? That way, we can prevent accidental regressions.

Please let me know if you need any help with this.

P.S. I've created a ticket on our side to track this: [SQQGGHA-2](https://jira.sonarsource.com/browse/SQQGGHA-2)

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on action.yml
> +  qualityGateStatus:
GitHub Actions tend to prefer lowercase and hyphened variables, rather than camelcased ones. Let's use this instead:

```suggestion
  quality-gate-status:
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on README.md
> +    # Individual step to check the quality gate
Small wording update:

```suggestion
    # Check the Quality Gate status
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on README.md
> +      id: sqQualityGateCk
Nitpick:

```suggestion
      id: sonarqube-quality-gate-check
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on README.md
> +      run: echo "The Status is ${{ steps.sqQualityGateCk.outputs.qualityGateStatus }}"
```suggestion
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on script/check-quality-gate.sh
> +   echo '::set-output name=qualityGateStatus::PASSED'
```suggestion
   echo '::set-output name=quality-gate-status::PASSED'
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on script/check-quality-gate.sh
> +   echo '::set-output name=qualityGateStatus::WARN'
```suggestion
   echo '::set-output name=quality-gate-status::WARN'
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on script/check-quality-gate.sh
> +   echo '::set-output name=qualityGateStatus::FAILED'
```suggestion
   echo '::set-output name=quality-gate-status::FAILED'
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on script/check-quality-gate.sh
> +   echo '::set-output name=qualityGateStatus::FAILED'
```suggestion
   echo '::set-output name=quality-gate-status::FAILED'
```

2022-07-04 08:41 UTC, wouter-admiraal-sonarsource commented on README.md
> +  run: echo "The Status is ${{ steps.sqQualityGateCk.outputs.qualityGateStatus }}"
Let's drop this. It's already explained above, no point in repeating it.

2022-07-14 06:43 UTC, wouter-admiraal-sonarsource commented
Hi again. I've taken the liberty to fork your fork, and make the suggested updates over there 🙂. You can follow the new PR [here](https://github.com/SonarSource/sonarqube-quality-gate-action/pull/17). I'll close this one. Thanks again for your contribution!

2022-07-14 06:43 UTC, closed without merging